### ISSUE TITLE
About Hunger NG

### ISSUE THREAD

**Issue by ghost** [AnnalysaTheMinetester/cheese#12]
I noticed that when using Hunger_NG with the Cheese Mod here, it doesn't work.

In the init.lua line 18, there stands,
cheese.hg_ng  = minetest.get_modpath("hunger_ng") ~= nil

but in the items.lua in line 103, line 357 and line 437, there stands,
if cheese.hunger_ng then

I don't know if that's the reason why it's not working.
But one thing I noticed, but guess it's more an Issue from Hunger_NG, is that the return function works, but only with one Item.
With something that can give you more Items back, like fondue with 3 bronze ingots, it's not working like it should, in other words, you can still eat even with full inventory, even though the return function from Hunger_NG should prevent this and you don't get the Items back.

**Comment by BlockAndPixelAge** [comment]
@AnnalysaTheMinetester 

I "fixed" the hunger_ng support a little in the init.lua.
https://github.com/BlockAndPixelAge/cheese/tree/BlockAndPixelAge-hunger_ng-patch
I changed in line 18 cheese.hg_ng to cheese.hunger_ng so it works now.

The only thing I can't fix, is with the fondue.

Tried with 

returns = "default:copper_ingot", "default:copper_ingot", "default:copper_ingot",

and with

returns = "default:copper_ingot", returns = "default:copper_ingot", returns = "default:copper_ingot",

But it will only give one ingot back.

And if you're asking, why I don't do a pull request, well I don't want to count as a contributor and I plan to delete my account and don't know if a ghost would stand there as a contributor.

**Comment by ghost** [comment]
@AnnalysaTheMinetester

I "fixed" the hunger_ng support a little in the init.lua.
https://github.com/BlockAndPixelAge/cheese/tree/BlockAndPixelAge-hunger_ng-patch
I changed in line 18 cheese.hg_ng to cheese.hunger_ng so it works now.

The only thing I can't fix, is with the fondue.

Tried with

returns = "default:copper_ingot", "default:copper_ingot", "default:copper_ingot",

and with

returns = "default:copper_ingot", returns = "default:copper_ingot", returns = "default:copper_ingot",

But it will only give one ingot back.

And if you're asking, why I don't do a pull request, well I don't want to count as a contributor and I plan to delete my account and don't know if a ghost would stand there as a contributor.

**Comment by AnnalysaTheMinetester** [comment]
Greetings!
First of all i want to apologize for my absence, and for not responding to this thread sooner.
Yes, you both are correct, i made a mistake by naming the hunger_ng variable differently in its declaration and usage.
It is also true that for the way hunger_ng is coded to return items, it doesnt allow for multiple items and i cant find a way to by pass the problem.
My options at this point are either let the foundue return only one ingot, effectly making the players loose ingots by crafting it if the server has hunger_ng, or rewrite the fondue to be crafted with only 1 ingot to begin with.
I think i choose the second one, please let me know your thoughts.

Thank you both for spending some of your time on my mod and actually wanting to fix it.

**Comment by BlockAndPixelAge** [comment]
@AnnalysaTheMinetester 

I thought, only few minutes ago, even of maybe a bowl, crafted from copper ingots (or what item you prefer), which can be put into the furnace to get the same amount of copper ingots back. Little problem is, creating a possible copper bowl recipe, without conflicting with other mods, that could use the same recipe.

In case of fondue recipe, three cheese group items, and one copper bowl for fondue, and getting the copper bowl back, with and without hunger_ng.

Oh, and the ghost is actually an old Account from me, which I deleted, otherwise I wouldn't know that deleted Accounts get replaced with ghost. :P

**Comment by ghost** [comment]
@AnnalysaTheMinetester

I thought, only few minutes ago, maybe using the bucket and three cheese group items. :P

Yeah I know, silly idea.

Other thing would be, making one item, like a bowl, specific for fondue, that can be used in the recipe.
Three cheese and the bowl.
But the recipe for the bowl alone, if it's only using Minetest Game items, and the risk that it could share it's recipe with another mod.
Maybe three copper ingots in the crafting grid, in the shape how you craft the bucket and a stick, in the upper left or right corner.
That way, it will be only one item that you get back, because it's only one bowl, and it works with the return function from hunger_ng.
And putting the bowl in the furnace, give you back the three copper ingots. :D

**Comment by AnnalysaTheMinetester** [comment]
Hi!
Registering another item seems to be the best solution for keeping the three ingots.
When i made the fondue, i just didnt want to make yet another item that has one, and one use only, hence the current crafting.
I could just make the fondue pot and leave it at that, but this fact bothers me. 
What do you think? Is it a non issue?

**Comment by BlockAndPixelAge** [comment]
@AnnalysaTheMinetester 

Registering a new item, the only thing that would bother me, is the possibility of shared recipe with other mods, otherwise it would be a non issue.

Well the silly idea with the bucket, could work too, still 3 ingots, just not copper, and it don't need to register a new item.
If the bucket would be used for the recipe, then I guess the color of the fondue pot texture, from the fondue, needs to be changed to fit the bucket color.
One bucket, three cheese, and it returns the bucket afterwards, after eating it.

That would be the other idea, and the bucket mod is already a dependency. :D

**Comment by ghost** [comment]
@AnnalysaTheMinetester

Registering a new item, the only thing that would bother me, is the possibility of shared recipe with other mods, otherwise it would be a non issue.

Well the silly idea with the bucket, could work too, still 3 ingots, just not copper, and it don't need to register a new item.
If the bucket would be used for the recipe, then I guess the color of the fondue pot texture, from the fondue, needs to be changed to fit the bucket color.
One bucket, three cheese, and it returns the bucket afterwards, after eating it.

That would be the other idea, and the bucket mod is already a dependency. :D

**Comment by AnnalysaTheMinetester** [comment]
Closing as this is now solved.
