### ISSUE TITLE
A couple of very minor typos

### ISSUE THREAD

**Issue by axcore** [AnnalysaTheMinetester/cheese#5]
In README.md, the license is probably spelled wrong (GLGP, should probably LGPL)

In milk_cauldron.lua, line 547, the string begins with a space character, so it won't be translated. Should be:

`    slot_state = remaining_inputs .. S("Stacks in Input Slots")`

**Comment by AnnalysaTheMinetester** [comment]
Hello! Thank you for reaching out and taking some of your time to check out my mod! I think i solved those issues. If you got any problems, please reach out to me again! Thank you!

**Comment by AnnalysaTheMinetester** [comment]
Fixed with current commit
